server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_lab
    username: root
    password: r00t#1234
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  autoconfigure:
    exclude: javax.sql.DataSource.class
